-- AlterTable
ALTER TABLE "public_site_settings" ADD COLUMN     "footer_content_text" TEXT NOT NULL DEFAULT '#E2E8F0',
ADD COLUMN     "footer_copyright_text" TEXT NOT NULL DEFAULT '#CBD5E0',
ADD COLUMN     "footer_header_text" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "footer_logo_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "footer_logo_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "footer_logo_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "footer_social_btn_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "footer_social_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "footer_social_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "header_hover_bg" TEXT NOT NULL DEFAULT '#A7D3F5',
ADD COLUMN     "header_hover_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "header_logo_bg" TEXT NOT NULL DEFAULT '#6FA8DC',
ADD COLUMN     "header_logo_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "header_logo_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "header_logo_text" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "header_text_color" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_about_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_about_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_about_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_about_btn_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_about_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_about_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_about_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_about_content_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_about_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_about_info_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_about_info_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_about_info_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_about_stat_card_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_about_stat_card_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_about_stat_card_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_about_stat_label_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_about_stat_number_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_cert_all_btn_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_cert_all_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_all_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_all_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_cert_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_cert_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_cert_card_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_cert_card_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_card_content_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_cert_card_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_cert_card_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_cert_view_btn_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_cert_view_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_view_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cert_view_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_cta_btn_bg" TEXT NOT NULL DEFAULT '#6FA8DC',
ADD COLUMN     "home_cta_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cta_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_cta_btn_text" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_cta_content_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_cta_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_exp_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_exp_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_exp_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_exp_btn_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_exp_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_exp_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_exp_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_exp_card_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_exp_card_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_exp_card_content_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_exp_card_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_exp_card_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_exp_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_hero_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_hero_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_hero_btn_bg" TEXT NOT NULL DEFAULT '#6FA8DC',
ADD COLUMN     "home_hero_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_btn_text" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_hero_card_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_hero_card_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_card_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_card_width" TEXT NOT NULL DEFAULT 'medium',
ADD COLUMN     "home_hero_content_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_hero_exp_badge_bg" TEXT NOT NULL DEFAULT '#6FA8DC',
ADD COLUMN     "home_hero_exp_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_exp_badge_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_hero_exp_badge_text" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_hero_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_portfolio_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_portfolio_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_portfolio_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_portfolio_btn_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_portfolio_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_portfolio_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_portfolio_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_portfolio_card_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_portfolio_card_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_portfolio_card_content_text" TEXT NOT NULL DEFAULT '#4A5568',
ADD COLUMN     "home_portfolio_card_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_portfolio_card_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_portfolio_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_portfolio_tech_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_portfolio_tech_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_portfolio_tech_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_tools_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_tools_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_tools_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_tools_btn_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_tools_btn_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_tools_btn_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_tools_btn_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "home_tools_card_bg" TEXT NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN     "home_tools_card_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_tools_card_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_tools_card_shadow" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_tools_header_text" TEXT NOT NULL DEFAULT '#1A202C',
ADD COLUMN     "home_tools_tool_badge_bg" TEXT NOT NULL DEFAULT '#EAF4FB',
ADD COLUMN     "home_tools_tool_badge_border" TEXT NOT NULL DEFAULT '#B8C6DB',
ADD COLUMN     "home_tools_tool_badge_text" TEXT NOT NULL DEFAULT '#2C3E50',
ADD COLUMN     "section_divider_color" TEXT NOT NULL DEFAULT '#B8C6DB';

-- CreateTable
CREATE TABLE "site_logos" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'Rhn Fthn',
    "image_url" TEXT,
    "alt_text" TEXT NOT NULL DEFAULT 'Logo',
    "link_url" TEXT NOT NULL DEFAULT '/',
    "position" TEXT NOT NULL DEFAULT 'header',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "site_logos_pkey" PRIMARY KEY ("id")
);
